version: '3.8'
services:
  hb-user:
    image: maheshchabbi/hb.user:latest
    container_name: hb-user
##   build:
##      context: ./user
##    environment:
 ##     - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9002:9002"
    restart: unless-stopped
    depends_on:
      - hb-eureka-server
      - hb-frontend


  hb-eureka-server:
    image: maheshchabbi/hb.eureka-server
    container_name: hb-eureka-server
 ##   build: ./eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    ports:
      - "9200:9200"

  hb-frontend:
    image: maheshchabbi/hb.frontend:latest
    container_name: hb-frontend
 ##   build: ./eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    ports:
      - "3000:3000"

  hb-apigw:
    image: maheshchabbi/hb.apigw
    container_name: hb-apigw
    build: ./apigw
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - hb-eureka-server





  hb-zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: hb-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  hb-broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: hb-broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - hb-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'hb-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hb-broker:9092,PLAINTEXT_INTERNAL://hb-broker:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.0.110:9092,PLAINTEXT_INTERNAL://hb-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  hb-zipkin:
    image: openzipkin/zipkin
    container_name: hb-zipkin
    restart: unless-stopped
    ports:
      - "9201:9411"