
server:
  port:
    9004

spring:
  application:
    name: archival
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://booking.cp6qemaye14q.ap-south-1.rds.amazonaws.com:3306/booking?createDatabaseIfNotExist=true
    username: admin
    password: maheshchabbi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  data:
    cassandra:
      keyspace-name: booking_keyspace
      contact-points: cassandra.us-east-1.amazonaws.com
      port: 9142
      local-datacenter: us-east-1
      username: YOUR_AWS_ACCESS_KEY
      password: YOUR_AWS_SECRET_KEY
      ssl-enabled: true
      schema-action: CREATE_IF_NOT_EXISTS

  zipkin:
    base-url: http://hb-zipkin:9411

  kafka:
    bootstrap-servers: http://hb-broker:9092

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
