server:
  port: 9003

spring:
  application:
    name: booking
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myeksrds-1.cp6qemaye14q.ap-south-1.rds.amazonaws.com:3306/booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: Maheshchabbi
  jpa:
    hibernate:
      ddl-auto: update  # Consider managing schema changes via migrations in production
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: cluster-hotel.uyazel.0001.aps1.cache.amazonaws.com  # Updated primary AWS ElastiCache endpoint
      port: 6379
      timeout: 3000  # Timeout in milliseconds
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          time-between-eviction-runs: 60000
  zipkin:
    base-url: http://hb-zipkin:9411
  kafka:
    bootstrap-servers: hb-broker:9092
  cache:
    type: redis
    cache-names:
      - bookingId
      - hotel-booking
      - user-booking
    redis:
      host: cluster-hotel.uyazel.0001.aps1.cache.amazonaws.com  # Updated AWS ElastiCache endpoint
      port: 6379
      time-to-live: 10000  # Cache expiry in milliseconds
      cache-null-values: true

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG

custom:
  redis:
    host: cluster-hotel.uyazel.0001.aps1.cache.amazonaws.com  # Updated primary AWS ElastiCache endpoint
    port: 6379
  paypal:
    mode: sandbox
    client:
      id: AU3lFjUm-hpp4z8Pls4QMHeqqqpKxrt167x8At0meKHLVFbPeBBawprvPbUSehMpIU1BS6SO--beEupW
      secret: EMid4txa6eaYtjwCXWSWOi69TicrlPIR86gcFvsmexKuvK4I98vMFm8G-q6QY1_Cy3BTP6uaU0cYSw9c
    host: http://10.0.0.110:9000
    frontend: http://localhost:3000
  security:
    rsa:
      public-key: classpath:certs/public.pem
    roles:
      - ADMIN
      - APP_USER
      - HOTEL_MANAGER
