server:
  port: 9001

spring:
  application:
    name: hotel
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hotel.cp6qemaye14q.ap-south-1.rds.amazonaws.com:3306/hotel?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: maheshchabbi
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  zipkin:
    base-url: http://hb-zipkin:9411

  kafka:
    bootstrap-servers: hb-broker:9092

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


logging:
  level:
    org:
      springframework:
        security: DEBUG

custom:
  security:
    rsa:
      public-key: classpath:certs/public.pem
    roles:
      - ADMIN
      - APP_USER
      - HOTEL_MANAGER
  file:
    path: "data"
    imageUrlPrefix: "http://hb-apigw:9000/api/v1/hotel/image"
