server:
  port: 9007

spring:
  application:
    name: search
  banner:
    location: classpath:banner.txt
  zipkin:
    base-url: http://hb-zipkin:9411

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

custom:
  build:
    flavor: oss
  elasticsearch:
    host: search-hotel-r5mlvbrrpaqflefx2k6emieoje.ap-south-1.es.amazonaws.com
    port: 443
    useSsl: true
    username: admin
    password: Adminisgr8*

logging:
  level:
    org.elasticsearch: DEBUG
    com.dlim2012.search: DEBUG

