server:
  port:
    9007

spring:
  application:
    name: search
  banner:
    location: classpath:banner.txt
  zipkin:
    base-url: http://hb-zipkin:9411

eureka:
  instance:
    hostname: hb-eureka-server
    port: 9200
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


custom:
  elasticsearch:
    host: search-hotel1-nzonzgcx4dksqjda333y5txcsu.ap-south-1.es.amazonaws.com
    useSsl: true